AWSTemplateFormatVersion: 2010-09-09
Description: "Example microservice deploy"

Transform:
  - UpdateDeploymentTransform

Parameters:
  ProjectName:
    Type: String
    Description:
      "Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment"

  LambdasBucketName:
    Type: String
    Description: "The S3 bucket from which to fetch the templates used by this stack."

  BucketBasePath:
    Type: String
    Description: "The S3 bucket base path where lambda functions are stored"

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: "Disambiguation useful for load balancer rules"

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: "The S3 bucket from which to fetch the templates used by this stack."

  #SNS Topic Alarm Arn and Name
  AlarmSNSTopicArn:
    Type: String
    Description: "An ARN of an SNS topic where to send alarm when log line includes ERROR or FATAL"

  Version:
    Type: String
    Description: "Keep versioning of commitIds used for cloudformation templates"

  LogsKinesisSourceStreamArn:
    Type: String
    Description: "Kinesis stream that receive logs"

  # - Log exports parameters
  CloudwatchFilterPattern:
    Default: ""
    Type: String
    Description: filter expression for exported logs

  ProgressionSensorDataDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing notifications metadata

  ProgressionSensorDataDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing notifications metadata

  CdcKinesisSourceStreamArn:
    Type: String
    Description: "Where to send CDC"

  CdcKinesisSourceStreamKeyArn:
    Description: "Kinesis source CDC stream crypto key ARN"
    Type: String

  CdcProgressionSensorKinesisSourceStreamArn:
    Type: String
    Description: "Where to send CDC"

  CdcProgressionSensorKinesisSourceStreamKeyArn:
    Description: "Kinesis source CDC stream crypto key ARN"
    Type: String

Conditions:
  SendLogToKinesis: !Not [!Equals [!Ref LogsKinesisSourceStreamArn, ""]]

Resources:
  #########################################################
  ###              SearchSLAViolationsLambda            ###
  #########################################################

  # Lambda function
  SearchSLAViolationsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-searchSLAViolationsLambda"
      Runtime: nodejs18.x
      Handler: "index.handler"
      Code:
        S3Bucket: !Ref LambdasBucketName
        S3Key: !Sub "${BucketBasePath}/searchSLAViolations.zip"
      Role: !GetAtt SearchSLAViolationsLambdaRole.Arn
      TracingConfig:
        Mode: Active
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:339249233099:layer:LambdaInsightsExtension:13"
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          DYNAMODB_TABLE: !Sub "${ProgressionSensorDataDynamoTableName}"
      Timeout : 10

  # Lambda function role
  SearchSLAViolationsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-SearchSLAViolationsLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /

  # Lambda function IAM policy
  SearchSLAViolationsLambdaRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${ProjectName}-SearchSLAViolationsLambdaRolePolicy
      Roles:
        - !Ref SearchSLAViolationsLambdaRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "dynamodb:Query"
            Resource:
              - !Sub "${ProgressionSensorDataDynamoTableArn}"
              - !Sub "${ProgressionSensorDataDynamoTableArn}/*"

  # lambda function Log Group
  SearchSLAViolationsLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SearchSLAViolationsLambda}"
      RetentionInDays: 14

  # Lambda function CloudWatch Logs Metric Filter
  SearchSLAViolationsLambdaFatalLogsMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref SearchSLAViolationsLambdaLogGroup
      FilterPattern: "?ERROR ?FATAL ?CRITICAL"
      MetricTransformations:
        - MetricValue: 1
          MetricNamespace: "ErrorFatalLogs"
          MetricName: !Sub ${ProjectName}-progressionSensor-SearchSLAViolationsFatalMetric

  # Lambda function CloudWatch alarm
  SearchSLAViolationsErrorFatalLogsMetricAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: SearchSLAViolationsLambdaFatalLogsMetricFilter
    Properties:
      AlarmName: !Sub ${ProjectName}-progressionSensor-SearchSLAViolationsErrorFatalLogsMetricAlarm
      AlarmDescription: "CloudWatch alarm for SearchSLAViolations Lambda logs with ERROR or FATAL line."
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      OKActions:
        - !Ref AlarmSNSTopicArn
      DatapointsToAlarm: 1
      MetricName: !Sub ${ProjectName}-progressionSensor-SearchSLAViolationsErrorFatalMetric
      Namespace: ErrorFatalLogs
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  SearchSLAViolationsSubscriptionFilter:
    Condition: SendLogToKinesis
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      RoleArn: !GetAtt SubscriptionFilterServiceRole.Arn
      LogGroupName: !Ref SearchSLAViolationsLambdaLogGroup
      FilterPattern: !Ref CloudwatchFilterPattern
      DestinationArn: !Ref LogsKinesisSourceStreamArn

  #########################################################
  ###              ActivityStepManagerLambda            ###
  #########################################################

  # Lambda function
  ActivityStepManagerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-activityStepManagerLambda"
      Runtime: nodejs18.x
      Handler: "index.handler"
      Code:
        S3Bucket: !Ref LambdasBucketName
        S3Key: !Sub "${BucketBasePath}/activityStepManager.zip"
      Role: !GetAtt ActivityStepManagerLambdaRole.Arn
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          DYNAMODB_TABLE: !Ref ProgressionSensorDataDynamoTableName
      TracingConfig:
        Mode: Active
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:339249233099:layer:LambdaInsightsExtension:13"
      Timeout : 10

  # Lambda function role
  ActivityStepManagerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-activityStepManagerLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # Lambda function IAM policy
  ActivityStepManagerLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${ProjectName}-ActivityStepManagerLambdaPolicy
      Roles:
        - !Ref ActivityStepManagerLambdaRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "dynamodb:*"
            Resource:
              - !Ref ProgressionSensorDataDynamoTableArn
              - !Sub "${ProgressionSensorDataDynamoTableArn}/*"
          - Effect: Allow
            Action:
              - "dynamodb:GetItem"
            Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-Notifications
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-Notifications/*"
          - Effect: Allow
            Action:
              - kinesis:DescribeStream
              - kinesis:DescribeStreamSummary
              - kinesis:GetShardIterator
              - kinesis:GetRecords
              - kinesis:ListShards
              - kinesis:ListStreams
              - kinesis:SubscribeToShard
            Resource: !Ref CdcKinesisSourceStreamArn
          - Action: kms:Decrypt
            Effect: Allow
            Resource: !Ref CdcKinesisSourceStreamKeyArn

  # lambda function Log Group
  ActivityStepManagerLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ActivityStepManagerLambda}"
      RetentionInDays: 14

  # Lambda function CloudWatch Logs Metric Filter
  ActivityStepManagerFatalLogsMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref ActivityStepManagerLambdaLogGroup
      FilterPattern: "?ERROR ?FATAL ?CRITICAL"
      MetricTransformations:
        - MetricValue: 1
          MetricNamespace: "ErrorFatalLogs"
          MetricName: !Sub ${ProjectName}-progressionSensor-ActivityStepManagerFatalMetric

  # Lambda function CloudWatch alarm
  ActivityStepManagerErrorFatalLogsMetricAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: ActivityStepManagerFatalLogsMetricFilter
    Properties:
      AlarmName: !Sub ${ProjectName}-progressionSensor-ActivityStepManagerErrorFatalLogsMetricAlarm
      AlarmDescription: "CloudWatch alarm for Function 1 Lambda logs with ERROR or FATAL line."
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      OKActions:
        - !Ref AlarmSNSTopicArn
      DatapointsToAlarm: 1
      MetricName: !Sub ${ProjectName}-progressionSensor-ActivityStepManagerErrorFatalMetric
      Namespace: ErrorFatalLogs
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  ### IAM Role used by Subscription filters to allow read logs from Cloudwatch and send logs to Kinesis Firehose
  SubscriptionFilterServiceRole:
    Condition: SendLogToKinesis
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: logs.amazonaws.com
        Version: "2012-10-17"
      Path: /
      Policies:
        - PolicyName: !Sub "${ProjectName}-progression-sensor-logs-subscription-role"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - kinesis:PutRecord
                Effect: Allow
                Resource: "*"
              - Action:
                  - "kms:Encrypt"
                  - "kms:GenerateDataKey"
                  - "kms:Decrypt"
                Effect: Allow
                Resource: "*"

  ActivityStepManagerSubscriptionFilter:
    Condition: SendLogToKinesis
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      RoleArn: !GetAtt SubscriptionFilterServiceRole.Arn
      LogGroupName: !Ref ActivityStepManagerLambdaLogGroup
      FilterPattern: !Ref CloudwatchFilterPattern
      DestinationArn: !Ref LogsKinesisSourceStreamArn

  # CDC to Activity Step Manager
  ActivityStepManagerLambdaKinesisSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 20
      BisectBatchOnFunctionError: true
      EventSourceArn: !Ref CdcKinesisSourceStreamArn
      FunctionName: !Ref ActivityStepManagerLambda
      FunctionResponseTypes:
        - ReportBatchItemFailures
      MaximumBatchingWindowInSeconds: 300 # 1 minute
      StartingPosition: LATEST

  #########################################################
  ###              SLAViolationCheckerLambda            ###
  #########################################################

  # Lambda function (from Kinesis)
  SLAViolationCheckerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-slaViolationCheckerLambda"
      Runtime: nodejs18.x
      Handler: "index.handler"
      Code:
        S3Bucket: !Ref LambdasBucketName
        S3Key: !Sub "${BucketBasePath}/slaViolationChecker.zip"
      Role: !GetAtt SLAViolationCheckerLambdaRole.Arn
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          DYNAMODB_TABLE: !Ref ProgressionSensorDataDynamoTableName
          INVOCATION_TYPE: "Kinesis"
      TracingConfig:
        Mode: Active
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:339249233099:layer:LambdaInsightsExtension:13"
      Timeout : 10

  # Lambda function (from SQS)
  SLAViolationCheckerLambdaSQS:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-slaViolationCheckerLambdaSQS"
      Runtime: nodejs18.x
      Handler: "index.handler"
      Code:
        S3Bucket: !Ref LambdasBucketName
        S3Key: !Sub "${BucketBasePath}/slaViolationChecker.zip"
      Role: !GetAtt SLAViolationCheckerLambdaRole.Arn
      Environment:
        Variables:
          REGION: !Sub ${AWS::Region}
          DYNAMODB_TABLE: !Ref ProgressionSensorDataDynamoTableName
          INVOCATION_TYPE: "SQS"
      TracingConfig:
        Mode: Active
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:339249233099:layer:LambdaInsightsExtension:13"

  # Lambda function role
  SLAViolationCheckerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-slaViolationCheckerLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # Lambda function IAM policy
  SLAViolationCheckerLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${ProjectName}-SLAViolationCheckerLambdaPolicy
      Roles:
        - !Ref SLAViolationCheckerLambdaRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "dynamodb:PutItem"
              - "dynamodb:UpdateItem"
            Resource:
              - !Ref ProgressionSensorDataDynamoTableArn
              - !Sub "${ProgressionSensorDataDynamoTableArn}/*"
          - Effect: Allow
            Action:
              - "dynamodb:GetItem"
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/pn-Timelines"
          - Effect: Allow
            Action:
              - kinesis:DescribeStream
              - kinesis:DescribeStreamSummary
              - kinesis:GetShardIterator
              - kinesis:GetRecords
              - kinesis:ListShards
              - kinesis:ListStreams
              - kinesis:SubscribeToShard
            Resource: !Ref CdcProgressionSensorKinesisSourceStreamArn
          - Action: kms:Decrypt
            Effect: Allow
            Resource: !Ref CdcProgressionSensorKinesisSourceStreamKeyArn

  # lambda function Log Group
  SLAViolationCheckerLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SLAViolationCheckerLambda}"
      RetentionInDays: 14

  # Lambda function CloudWatch Logs Metric Filter
  SLAViolationCheckerFatalLogsMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref SLAViolationCheckerLambdaLogGroup
      FilterPattern: "?ERROR ?FATAL ?CRITICAL"
      MetricTransformations:
        - MetricValue: 1
          MetricNamespace: "ErrorFatalLogs"
          MetricName: !Sub ${ProjectName}-progressionSensor-SLAViolationCheckerFatalMetric

  # Lambda function CloudWatch alarm
  SLAViolationCheckerErrorFatalLogsMetricAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: SLAViolationCheckerFatalLogsMetricFilter
    Properties:
      AlarmName: !Sub ${ProjectName}-progressionSensor-SLAViolationCheckerErrorFatalLogsMetricAlarm
      AlarmDescription: "CloudWatch alarm for SLAViolationChecker Lambda logs with ERROR or FATAL line."
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      OKActions:
        - !Ref AlarmSNSTopicArn
      DatapointsToAlarm: 1
      MetricName: !Sub ${ProjectName}-progressionSensor-SLAViolationCheckerErrorFatalMetric
      Namespace: ErrorFatalLogs
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  SLAViolationCheckerSubscriptionFilter:
    Condition: SendLogToKinesis
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      RoleArn: !GetAtt SubscriptionFilterServiceRole.Arn
      LogGroupName: !Ref SLAViolationCheckerLambdaLogGroup
      FilterPattern: !Ref CloudwatchFilterPattern
      DestinationArn: !Ref LogsKinesisSourceStreamArn

  # CDC to SLA Violation Checker
  SLAViolationCheckerLambdaKinesisSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 20
      BisectBatchOnFunctionError: true
      EventSourceArn: !Ref CdcProgressionSensorKinesisSourceStreamArn
      FunctionName: !Ref SLAViolationCheckerLambda
      FunctionResponseTypes:
        - ReportBatchItemFailures
      MaximumBatchingWindowInSeconds: 300 # 1 minute
      StartingPosition: LATEST

  # for the complete implementation, also attach to SQS
  # ...
