AWSTemplateFormatVersion: "2010-09-09"
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: "keep track of used projects commitIds"

  CdcProgressionSensorStreamRetentionHours:
    Type: Number
    Description: "Change Data Capture Kinesis Data Stream retention period in hours"
    Default: "72"

  AlarmSNSTopicName:
    Type: String
    Description: "Topic alarm"

Resources:
  ## KINESIS SOURCE STREAM FOR Change Data Capture
  CdcProgressionSensorKinesisSourceStream:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-stream.yaml"
      Parameters:
        StreamName: !Sub "${ProjectName}-cdc-progression-sensor-stream"
        StreamRetentionPeriodHours: !Ref CdcProgressionSensorStreamRetentionHours

  ProgressionSensorDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-ProgressionSensorData"
      AttributeDefinitions:
        # primary key
        - AttributeName: "entityName_type_relatedEntityId" # entity type (step or sla violation) concatenated to step type and then to IUN
          AttributeType: "S"
        - AttributeName: "id" # string concatenation based on step type
          AttributeType: "S"
        # secondary keys
        - AttributeName: "sla_relatedEntityId" # IUN
          AttributeType: "S"
        - AttributeName: "type_endTimestampYearMonth"
          AttributeType: "S"
        - AttributeName: "endTimeStamp" # bool
          AttributeType: "S"
        - AttributeName: "alarmTTLYearToMinute"
          AttributeType: "S"
        - AttributeName: "alarmTTL" # alarmTTL set both for steps and SLA; step_alarmTTL only set for steps (and TTL is set on step_alarmTTL, so it's an 'N' type)
          AttributeType: "S"
        - AttributeName: "active_sla_entityName_type"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "entityName_type_relatedEntityId"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        # violations read patterns
        - IndexName: "iun-index"
          KeySchema:
            - AttributeName: "sla_relatedEntityId"
              KeyType: "HASH"
            - AttributeName: "alarmTTL"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "activeViolations-index"
          KeySchema:
            - AttributeName: "active_sla_entityName_type" # new field for SLA Violations, to be removed when endTimestamp is set (and the SLA Violation is historicized)
              KeyType: "HASH"
            - AttributeName: "alarmTTL"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "partitionedEndTimeStamp-index"
          KeySchema:
            - AttributeName: "type_endTimestampYearMonth" # TYPE##2023-01 - present only for storicized SLA Violations (when endTimestamp != null)
              KeyType: "HASH"
            - AttributeName: "endTimeStamp"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        # activity step read pattern
        - IndexName: "alarmTTL-index"
          KeySchema:
            - AttributeName: "alarmTTLYearToMinute" # from ISO timestamp, with 00# (hex) deterministic prefix, generated starting from IUN (00#[ISOTIMESTAMPYearTominute])
              KeyType: "HASH"
            - AttributeName: "id" # no longer alarmTTLSecondsAndMilliseconds from ISO timestamp
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "step_alarmTTL"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      KinesisStreamSpecification:
        StreamArn: !GetAtt CdcProgressionSensorKinesisSourceStream.Outputs.KinesisStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      Tags:
        - Key: pnInfraFeature
          Value: pnStorage
        - Key: pnMicroservice
          Value: !Sub "${ProjectName}-ProgressionSensorData"

# SQS Queue
  ProgressionSensorQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-progression-sensor-queue'
        DelaySeconds: 10

Outputs:
  ProgressionSensorDataDynamoTableName:
    Description: Name of dynamodb table containing notifications metadata
    Value: !Ref ProgressionSensorDataTable
  ProgressionSensorDataDynamoTableArn:
    Description: ARN of dynamodb table containing notifications metadata
    Value: !Sub "${ProgressionSensorDataTable.Arn}"

  # Kinesis Source Stream containing the DynamoDB Change Data Capture events
  CdcProgressionSensorKinesisSourceStreamName:
    Description: "Kinesis source CDC stream name"
    Value: !GetAtt CdcProgressionSensorKinesisSourceStream.Outputs.KinesisStreamName
  CdcProgressionSensorKinesisSourceStreamArn:
    Description: "Kinesis source CDC stream ARN"
    Value: !GetAtt CdcProgressionSensorKinesisSourceStream.Outputs.KinesisStreamArn
  CdcProgressionSensorKinesisSourceStreamKeyArn:
    Description: "Kinesis source CDC stream crypto key ARN"
    Value: !GetAtt CdcProgressionSensorKinesisSourceStream.Outputs.KinesisStreamKeyArn

  # Scheduled Actions
  ProgressionSensorQueueName:
    Value: !GetAtt ProgressionSensorQueue.Outputs.QueueName
    Description: pn-delivery-push actions queue name
  ProgressionSensorQueueURL:
    Value: !GetAtt ProgressionSensorQueue.Outputs.QueueURL
    Description: pn-delivery-push actions queue URL
  ProgressionSensorQueueARN:
    Value: !GetAtt ProgressionSensorQueue.Outputs.QueueARN
    Description: pn-delivery-push actions queue ARN
  ProgressionSensorQueueAlarmARN:
    Value: !GetAtt ProgressionSensorQueue.Outputs.SqsDLQAlarmArn
    Description: pn-delivery-push actions queue dlq alarm queue 
  ProgressionSensorQueueAgeAlarmARN:
    Value: !GetAtt ProgressionSensorQueue.Outputs.SqsAgeAlarmArn
    Description: pn-delivery-push actions queue age alarm ARN